// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.5
// source: messenger_dialog.proto

package messenger_dialog_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                       // Уникальный ID сообщения
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // ID отправителя
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`                    // Текст сообщения
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`          // Время отправки Timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_messenger_dialog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_dialog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_messenger_dialog_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Message) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type DialogInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DialogId      int32                  `protobuf:"varint,1,opt,name=dialog_id,json=dialogId,proto3" json:"dialog_id,omitempty"`         // Уникальный ID диалога
	PeerId        int32                  `protobuf:"varint,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`               // ID собеседника
	PeerLogin     string                 `protobuf:"bytes,3,opt,name=peer_login,json=peerLogin,proto3" json:"peer_login,omitempty"`       // Логин собеседника
	LastMessage   string                 `protobuf:"bytes,4,opt,name=last_message,json=lastMessage,proto3" json:"last_message,omitempty"` // Текст последнего сообщения
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DialogInfo) Reset() {
	*x = DialogInfo{}
	mi := &file_messenger_dialog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DialogInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialogInfo) ProtoMessage() {}

func (x *DialogInfo) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_dialog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialogInfo.ProtoReflect.Descriptor instead.
func (*DialogInfo) Descriptor() ([]byte, []int) {
	return file_messenger_dialog_proto_rawDescGZIP(), []int{1}
}

func (x *DialogInfo) GetDialogId() int32 {
	if x != nil {
		return x.DialogId
	}
	return 0
}

func (x *DialogInfo) GetPeerId() int32 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

func (x *DialogInfo) GetPeerLogin() string {
	if x != nil {
		return x.PeerLogin
	}
	return ""
}

func (x *DialogInfo) GetLastMessage() string {
	if x != nil {
		return x.LastMessage
	}
	return ""
}

type CreateDialogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`            // ID пользователя, который создает диалог
	PeerId        int32                  `protobuf:"varint,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`            // ID собеседника
	DialogName    string                 `protobuf:"bytes,3,opt,name=dialog_name,json=dialogName,proto3" json:"dialog_name,omitempty"` // Название диалога
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDialogRequest) Reset() {
	*x = CreateDialogRequest{}
	mi := &file_messenger_dialog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDialogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDialogRequest) ProtoMessage() {}

func (x *CreateDialogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_dialog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDialogRequest.ProtoReflect.Descriptor instead.
func (*CreateDialogRequest) Descriptor() ([]byte, []int) {
	return file_messenger_dialog_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDialogRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateDialogRequest) GetPeerId() int32 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

func (x *CreateDialogRequest) GetDialogName() string {
	if x != nil {
		return x.DialogName
	}
	return ""
}

type CreateDialogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                        // Статус, создан ли диалог
	DialogId      int32                  `protobuf:"varint,2,opt,name=dialog_id,json=dialogId,proto3" json:"dialog_id,omitempty"`      // ID созданного / найденного диалога
	DialogName    string                 `protobuf:"bytes,3,opt,name=dialog_name,json=dialogName,proto3" json:"dialog_name,omitempty"` // Название диалога
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDialogResponse) Reset() {
	*x = CreateDialogResponse{}
	mi := &file_messenger_dialog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDialogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDialogResponse) ProtoMessage() {}

func (x *CreateDialogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_dialog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDialogResponse.ProtoReflect.Descriptor instead.
func (*CreateDialogResponse) Descriptor() ([]byte, []int) {
	return file_messenger_dialog_proto_rawDescGZIP(), []int{3}
}

func (x *CreateDialogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateDialogResponse) GetDialogId() int32 {
	if x != nil {
		return x.DialogId
	}
	return 0
}

func (x *CreateDialogResponse) GetDialogName() string {
	if x != nil {
		return x.DialogName
	}
	return ""
}

type CheckDialogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // ID первого пользователя
	PeerId        int32                  `protobuf:"varint,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"` // ID второго пользователя
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckDialogRequest) Reset() {
	*x = CheckDialogRequest{}
	mi := &file_messenger_dialog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckDialogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDialogRequest) ProtoMessage() {}

func (x *CheckDialogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_dialog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDialogRequest.ProtoReflect.Descriptor instead.
func (*CheckDialogRequest) Descriptor() ([]byte, []int) {
	return file_messenger_dialog_proto_rawDescGZIP(), []int{4}
}

func (x *CheckDialogRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckDialogRequest) GetPeerId() int32 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

type CheckDialogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`                     // статус, есть ли диалог
	DialogId      int32                  `protobuf:"varint,2,opt,name=dialog_id,json=dialogId,proto3" json:"dialog_id,omitempty"` // выведет 0, если диалога нет, если есть, то его ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckDialogResponse) Reset() {
	*x = CheckDialogResponse{}
	mi := &file_messenger_dialog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckDialogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDialogResponse) ProtoMessage() {}

func (x *CheckDialogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_dialog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDialogResponse.ProtoReflect.Descriptor instead.
func (*CheckDialogResponse) Descriptor() ([]byte, []int) {
	return file_messenger_dialog_proto_rawDescGZIP(), []int{5}
}

func (x *CheckDialogResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *CheckDialogResponse) GetDialogId() int32 {
	if x != nil {
		return x.DialogId
	}
	return 0
}

type GetUserDialogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // ID пользователя
	Limit         *int32                 `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`           // Сколько диалогов загрузить (опционально)
	Offset        *int32                 `protobuf:"varint,3,opt,name=offset,proto3,oneof" json:"offset,omitempty"`         // Сколько диалогов пропустить (опционально)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDialogsRequest) Reset() {
	*x = GetUserDialogsRequest{}
	mi := &file_messenger_dialog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDialogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDialogsRequest) ProtoMessage() {}

func (x *GetUserDialogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_dialog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDialogsRequest.ProtoReflect.Descriptor instead.
func (*GetUserDialogsRequest) Descriptor() ([]byte, []int) {
	return file_messenger_dialog_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserDialogsRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserDialogsRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetUserDialogsRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

type GetUserDialogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dialogs       []*DialogInfo          `protobuf:"bytes,1,rep,name=dialogs,proto3" json:"dialogs,omitempty"` // список диалогов
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDialogsResponse) Reset() {
	*x = GetUserDialogsResponse{}
	mi := &file_messenger_dialog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDialogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDialogsResponse) ProtoMessage() {}

func (x *GetUserDialogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_dialog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDialogsResponse.ProtoReflect.Descriptor instead.
func (*GetUserDialogsResponse) Descriptor() ([]byte, []int) {
	return file_messenger_dialog_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserDialogsResponse) GetDialogs() []*DialogInfo {
	if x != nil {
		return x.Dialogs
	}
	return nil
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DialogId      int32                  `protobuf:"varint,1,opt,name=dialog_id,json=dialogId,proto3" json:"dialog_id,omitempty"` // ID диалога
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // ID отправителя
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`                          // Текст сообщения
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_messenger_dialog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_dialog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_messenger_dialog_proto_rawDescGZIP(), []int{8}
}

func (x *SendMessageRequest) GetDialogId() int32 {
	if x != nil {
		return x.DialogId
	}
	return 0
}

func (x *SendMessageRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SendMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int32                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // ID созданного сообщения
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                   // Время отправки
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_messenger_dialog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_dialog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_messenger_dialog_proto_rawDescGZIP(), []int{9}
}

func (x *SendMessageResponse) GetMessageId() int32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *SendMessageResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type GetDialogMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DialogId      int32                  `protobuf:"varint,1,opt,name=dialog_id,json=dialogId,proto3" json:"dialog_id,omitempty"` // ID диалога
	Login         string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`                        // логин пользователя (для проверки доступа)
	Limit         *int32                 `protobuf:"varint,3,opt,name=limit,proto3,oneof" json:"limit,omitempty"`                 // Сколько сообщение показать (опционально)
	Offset        *int32                 `protobuf:"varint,4,opt,name=offset,proto3,oneof" json:"offset,omitempty"`               // Сколько сообщений пропустить (опционально)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDialogMessagesRequest) Reset() {
	*x = GetDialogMessagesRequest{}
	mi := &file_messenger_dialog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDialogMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDialogMessagesRequest) ProtoMessage() {}

func (x *GetDialogMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_dialog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDialogMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetDialogMessagesRequest) Descriptor() ([]byte, []int) {
	return file_messenger_dialog_proto_rawDescGZIP(), []int{10}
}

func (x *GetDialogMessagesRequest) GetDialogId() int32 {
	if x != nil {
		return x.DialogId
	}
	return 0
}

func (x *GetDialogMessagesRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *GetDialogMessagesRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetDialogMessagesRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

type GetDialogMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"` // Список сообщений
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDialogMessagesResponse) Reset() {
	*x = GetDialogMessagesResponse{}
	mi := &file_messenger_dialog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDialogMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDialogMessagesResponse) ProtoMessage() {}

func (x *GetDialogMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_dialog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDialogMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetDialogMessagesResponse) Descriptor() ([]byte, []int) {
	return file_messenger_dialog_proto_rawDescGZIP(), []int{11}
}

func (x *GetDialogMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_messenger_dialog_proto protoreflect.FileDescriptor

const file_messenger_dialog_proto_rawDesc = "" +
	"\n" +
	"\x16messenger_dialog.proto\x12\x06dialog\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x84\x01\n" +
	"\n" +
	"DialogInfo\x12\x1b\n" +
	"\tdialog_id\x18\x01 \x01(\x05R\bdialogId\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\x05R\x06peerId\x12\x1d\n" +
	"\n" +
	"peer_login\x18\x03 \x01(\tR\tpeerLogin\x12!\n" +
	"\flast_message\x18\x04 \x01(\tR\vlastMessage\"h\n" +
	"\x13CreateDialogRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\x05R\x06peerId\x12\x1f\n" +
	"\vdialog_name\x18\x03 \x01(\tR\n" +
	"dialogName\"n\n" +
	"\x14CreateDialogResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\tdialog_id\x18\x02 \x01(\x05R\bdialogId\x12\x1f\n" +
	"\vdialog_name\x18\x03 \x01(\tR\n" +
	"dialogName\"F\n" +
	"\x12CheckDialogRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\x05R\x06peerId\"J\n" +
	"\x13CheckDialogResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x1b\n" +
	"\tdialog_id\x18\x02 \x01(\x05R\bdialogId\"}\n" +
	"\x15GetUserDialogsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x19\n" +
	"\x05limit\x18\x02 \x01(\x05H\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x03 \x01(\x05H\x01R\x06offset\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_offset\"F\n" +
	"\x16GetUserDialogsResponse\x12,\n" +
	"\adialogs\x18\x01 \x03(\v2\x12.dialog.DialogInfoR\adialogs\"^\n" +
	"\x12SendMessageRequest\x12\x1b\n" +
	"\tdialog_id\x18\x01 \x01(\x05R\bdialogId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"n\n" +
	"\x13SendMessageResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x05R\tmessageId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x9a\x01\n" +
	"\x18GetDialogMessagesRequest\x12\x1b\n" +
	"\tdialog_id\x18\x01 \x01(\x05R\bdialogId\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12\x19\n" +
	"\x05limit\x18\x03 \x01(\x05H\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x04 \x01(\x05H\x01R\x06offset\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_offset\"H\n" +
	"\x19GetDialogMessagesResponse\x12+\n" +
	"\bmessages\x18\x01 \x03(\v2\x0f.dialog.MessageR\bmessages2\x95\x03\n" +
	"\rDialogService\x12I\n" +
	"\fCreateDialog\x12\x1b.dialog.CreateDialogRequest\x1a\x1c.dialog.CreateDialogResponse\x12F\n" +
	"\vCheckDialog\x12\x1a.dialog.CheckDialogRequest\x1a\x1b.dialog.CheckDialogResponse\x12O\n" +
	"\x0eGetUserDialogs\x12\x1d.dialog.GetUserDialogsRequest\x1a\x1e.dialog.GetUserDialogsResponse\x12F\n" +
	"\vSendMessage\x12\x1a.dialog.SendMessageRequest\x1a\x1b.dialog.SendMessageResponse\x12X\n" +
	"\x11GetDialogMessages\x12 .dialog.GetDialogMessagesRequest\x1a!.dialog.GetDialogMessagesResponseB\x1aZ\x18pkg/messenger_dialog_apib\x06proto3"

var (
	file_messenger_dialog_proto_rawDescOnce sync.Once
	file_messenger_dialog_proto_rawDescData []byte
)

func file_messenger_dialog_proto_rawDescGZIP() []byte {
	file_messenger_dialog_proto_rawDescOnce.Do(func() {
		file_messenger_dialog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messenger_dialog_proto_rawDesc), len(file_messenger_dialog_proto_rawDesc)))
	})
	return file_messenger_dialog_proto_rawDescData
}

var file_messenger_dialog_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_messenger_dialog_proto_goTypes = []any{
	(*Message)(nil),                   // 0: dialog.Message
	(*DialogInfo)(nil),                // 1: dialog.DialogInfo
	(*CreateDialogRequest)(nil),       // 2: dialog.CreateDialogRequest
	(*CreateDialogResponse)(nil),      // 3: dialog.CreateDialogResponse
	(*CheckDialogRequest)(nil),        // 4: dialog.CheckDialogRequest
	(*CheckDialogResponse)(nil),       // 5: dialog.CheckDialogResponse
	(*GetUserDialogsRequest)(nil),     // 6: dialog.GetUserDialogsRequest
	(*GetUserDialogsResponse)(nil),    // 7: dialog.GetUserDialogsResponse
	(*SendMessageRequest)(nil),        // 8: dialog.SendMessageRequest
	(*SendMessageResponse)(nil),       // 9: dialog.SendMessageResponse
	(*GetDialogMessagesRequest)(nil),  // 10: dialog.GetDialogMessagesRequest
	(*GetDialogMessagesResponse)(nil), // 11: dialog.GetDialogMessagesResponse
	(*timestamppb.Timestamp)(nil),     // 12: google.protobuf.Timestamp
}
var file_messenger_dialog_proto_depIdxs = []int32{
	12, // 0: dialog.Message.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 1: dialog.GetUserDialogsResponse.dialogs:type_name -> dialog.DialogInfo
	12, // 2: dialog.SendMessageResponse.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 3: dialog.GetDialogMessagesResponse.messages:type_name -> dialog.Message
	2,  // 4: dialog.DialogService.CreateDialog:input_type -> dialog.CreateDialogRequest
	4,  // 5: dialog.DialogService.CheckDialog:input_type -> dialog.CheckDialogRequest
	6,  // 6: dialog.DialogService.GetUserDialogs:input_type -> dialog.GetUserDialogsRequest
	8,  // 7: dialog.DialogService.SendMessage:input_type -> dialog.SendMessageRequest
	10, // 8: dialog.DialogService.GetDialogMessages:input_type -> dialog.GetDialogMessagesRequest
	3,  // 9: dialog.DialogService.CreateDialog:output_type -> dialog.CreateDialogResponse
	5,  // 10: dialog.DialogService.CheckDialog:output_type -> dialog.CheckDialogResponse
	7,  // 11: dialog.DialogService.GetUserDialogs:output_type -> dialog.GetUserDialogsResponse
	9,  // 12: dialog.DialogService.SendMessage:output_type -> dialog.SendMessageResponse
	11, // 13: dialog.DialogService.GetDialogMessages:output_type -> dialog.GetDialogMessagesResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_messenger_dialog_proto_init() }
func file_messenger_dialog_proto_init() {
	if File_messenger_dialog_proto != nil {
		return
	}
	file_messenger_dialog_proto_msgTypes[6].OneofWrappers = []any{}
	file_messenger_dialog_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messenger_dialog_proto_rawDesc), len(file_messenger_dialog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_messenger_dialog_proto_goTypes,
		DependencyIndexes: file_messenger_dialog_proto_depIdxs,
		MessageInfos:      file_messenger_dialog_proto_msgTypes,
	}.Build()
	File_messenger_dialog_proto = out.File
	file_messenger_dialog_proto_goTypes = nil
	file_messenger_dialog_proto_depIdxs = nil
}
